2025-08-18 08:07:25,884 - ERROR - Context: Test - Dosya okuma | Error: FileNotFoundError | Message: [Errno 2] No such file or directory: 'nonexistent_file.txt'
2025-08-18 08:07:25,884 - ERROR - Traceback: Traceback (most recent call last):
  File "C:\Users\brt_c\OneDrive\Masaüstü\soru_projesi\error_handler.py", line 301, in test_error_handler
    with open("nonexistent_file.txt", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'nonexistent_file.txt'

2025-08-18 08:07:28,998 - ERROR - Context: Test - Matematik işlemi | Error: ZeroDivisionError | Message: division by zero
2025-08-18 08:07:29,013 - ERROR - Traceback: Traceback (most recent call last):
  File "C:\Users\brt_c\OneDrive\Masaüstü\soru_projesi\error_handler.py", line 308, in test_error_handler
    result = 10 / 0
             ~~~^~~
ZeroDivisionError: division by zero

2025-08-18 08:07:30,921 - ERROR - Context: Test - Tip işlemi | Error: TypeError | Message: can only concatenate str (not "int") to str
2025-08-18 08:07:30,922 - ERROR - Traceback: Traceback (most recent call last):
  File "C:\Users\brt_c\OneDrive\Masaüstü\soru_projesi\error_handler.py", line 314, in test_error_handler
    result = "string" + 123
             ~~~~~~~~~^~~~~
TypeError: can only concatenate str (not "int") to str

